var dappInterface={
  /*
    specify ways your html elements are connected to your Ethereum contract. Expressions are evaluated as javascript.
  */
  "elementsById":{
    "myNapkinsDiv":{
      "display":"toDecimal(napkinCount(userAddress))"//calls the smart contract function 'napkinCount', with the current user's ethereum address as a parameter, converts it to a number, and sets the text content of the element with id 'myNapkinsDiv' to that number.
    },
  },
  "network":"Ropsten",//The network this contract is on. change to mainnet to connect to a contract on mainnet
  "contract":"0x20263a01e0923914A4AA64c0dc21eDf2F5F9F3FB",//the contract address
  //the ABI for the contract (can get from remix compile tab or etherscan)
  "abi":[{"constant":false,"inputs":[{"name":"referral","type":"address"}],"name":"buyNapkins","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[],"name":"getFreeNapkins","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"napkins","type":"uint256"},{"name":"addr","type":"address"}],"name":"moveNapkinsTo","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"potatoOwners","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"napkinCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"lastNapkinTime","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countdownTimeLeft","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"index","type":"uint256"}],"name":"buyPotato","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[],"name":"COUNTDOWN_TIME","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"napkins","type":"uint256"}],"name":"sellNapkins","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"balance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"NAPKIN_VALUE","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"message","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"countdownIsUp","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"potatoPrices","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}],
}
